### ISSUE TITLE
Add content type schema unarchive option

### ISSUE THREAD

**Issue by philipbushnell-valtech** [labd/terraform-provider-amplience#13]
It appears the provider doesn't unarchive a schema if it's added back to the terraform.

The provider fails with the following error:

![image](https://user-images.githubusercontent.com/78373345/148970305-1a4136b2-a544-4389-bcd2-c8d55cdd6ba5.png)

This occurs after the following steps:

- Add a schema (CREATE)
- Apply
- Destroy the schema (ARCHIVE)
- Apply
- Re-add the same schema (UNARCHIVE)
- Apply

@pimvernooij has suggested to raise this as the functionality has apparently not been implemented yet.

**Comment by tleguijt** [comment]
https://github.com/labd/terraform-provider-amplience/pull/15
