### ISSUE TITLE
Content types and schema are not synced when imported

### ISSUE THREAD

**Issue by philipbushnell-valtech** [labd/terraform-provider-amplience#14]
It appears the provider doesn't sync the content types and their schemas when terraform is applied and the changes are imported.

Steps to reproduce:

- Add a content type schema 
- Add a content type for the schema
- Apply
- Create content using this content type in Dynamic Content
- Update the schema (e.g. turn a string field into a number field)
- Apply
- Refresh in Dynamic Content and it's still the old schema (e.g. the string field, not a number field)

@pimvernooij has suggested to raise this as the functionality has apparently not been implemented yet.

**Comment by tleguijt** [comment]
Example https://github.com/amplience/dc-management-sdk-js/blob/master/src/lib/model/ContentType.ts#L138
