### ISSUE TITLE
Support for adjusting Device Sizes

### ISSUE THREAD

**Issue by benmaher-fg** [labd/terraform-provider-amplience#23]
It would be great if we could specify device sizes through the terraform provider for the embedded visualizer in Amplience. We've done some digging and found that it's possible to do so with the [content-management api](https://amplience.com/developers/docs/apis/content-management-reference/#tag/Hubs/operation/updateHubSettings). 

![image](https://github.com/labd/terraform-provider-amplience/assets/115991552/e657473f-f0d0-43f6-b638-fd67f4e1b629)

**Comment by demeyerthom** [comment]
Hi @benmaher-fg thanks for reaching out!

Currently setting hub settings is not supported by this terraform provider. However we are looking to add it soon, so this should be possible in the future!
